services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=todoapp
    networks:
      - todoapp-network
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - todoapp-network
    volumes:
      - data:/var/lib/redis/data
    
  api:
    image: todoapp-api
    environment:
      URL_DATABASE_POSTGRES: ${URL_DATABASE_POSTGRES}
      HOST_REDIS: ${HOST_REDIS}
      PORT_REDIS: ${PORT_REDIS}
    networks:
      - todoapp-network
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  
networks:
  todoapp-network:
    driver: bridge
  
volumes:
  data: