services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=dockerpassword
      - POSTGRES_DB=todoapp
    networks:
      - todoapp-network
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - todoapp-network
    volumes:
      - data:/var/lib/redis/data
    
  api:
    image: todoapp-api
    environment:
      URL_DATABASE: "postgresql+psycopg://dockeruser:dockerpassword@postgres:5432/todoapp"
      HOST_REDIS: "redis"
      PORT_REDIS: "6379"
    networks:
      - todoapp-network
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  
networks:
  todoapp-network:
    driver: bridge
  
volumes:
  data: