"""Add foreign key notes.uid -> user.uid

Revision ID: 0c7bea43c0fa
Revises: 5f3d9a9836cb
Create Date: 2025-10-13 20:17:30.859575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7bea43c0fa'
down_revision: Union[str, Sequence[str], None] = '5f3d9a9836cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_foreign_key(
        constraint_name="fk_notes_user_uid",
        source_table="notes",
        referent_table="user",
        local_cols=["uid"],
        remote_cols=["uid"],
        ondelete="CASCADE"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        constraint_name="fk_notes_user_uid",
        table_name="notes",
        type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
